In [2]:
import numpy as np

In [4]:
a=np.array([1,2,4])
print(a)
print(a.shape)
b=np.array([
    [1,2,3],
    [4,5,6]
])
print(b)
print(b.shape)

[1 2 4]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
c=np.arange(1,10,.2)#start,end ,step
print(c)
print(c.shape)
d=np.linspace(1,10,20)#start,end,number of elements
print(d)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
(45,)
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [12]:
print(c.ndim)

1


In [19]:
print(c.reshape(3,3,5))

[[[1.  1.2 1.4 1.6 1.8]
  [2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]
  [6.  6.2 6.4 6.6 6.8]]

 [[7.  7.2 7.4 7.6 7.8]
  [8.  8.2 8.4 8.6 8.8]
  [9.  9.2 9.4 9.6 9.8]]]


In [24]:
np.random.randint(1,1066,(3,3))

array([[739, 393, 947],
       [429, 568, 808],
       [355, 896, 358]])

maths in numpy


In [3]:
x=np.array([
    [2,3,4],
    [5,6,7]
])

y=np.array([
    [1,2,3],
    [4,5,6]
])

In [4]:
print(x+y) #element wise addition
print(x-y) #.............subtraction
print(x*y)#............multiplication
print(x/y)#............division
print(x**y)#element wise power
print(x%7) #element wise modulus

[[ 3  5  7]
 [ 9 11 13]]
[[1 1 1]
 [1 1 1]]
[[ 2  6 12]
 [20 30 42]]
[[2.         1.5        1.33333333]
 [1.25       1.2        1.16666667]]
[[     2      9     64]
 [   625   7776 117649]]
[[2 3 4]
 [5 6 0]]


In [5]:
print(x*2)#scalar multiplication
print(x/2)#scalar division
print(x**2)#scalar power
print(x%2) #scalar modulus

[[ 4  6  8]
 [10 12 14]]
[[1.  1.5 2. ]
 [2.5 3.  3.5]]
[[ 4  9 16]
 [25 36 49]]
[[0 1 0]
 [1 0 1]]


In [6]:
#matrix multiplication
print(x.dot(y.T))
print(np.matmul(x,y.T))
print(x @ y.T)

[[20 47]
 [38 92]]
[[20 47]
 [38 92]]
[[20 47]
 [38 92]]


In [7]:
#statistical function
print(x.sum()) #sum of all elements
print(x.sum(axis=0)) #sum of columns
print(x.sum(axis=1)) #sum of rows
print(x.mean()) #mean of all elements
print(x.std()) #standard deviation of all elements
print(x.min()) #minimum of all elements
print(x.max()) #max of all elements
 

27
[ 7  9 11]
[ 9 18]
4.5
1.707825127659933
2
7


In [8]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[[ 0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866 ]]
[[-0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225]]
[[-2.18503986 -0.14254654  1.15782128]
 [-3.38051501 -0.29100619  0.87144798]]


In [10]:
#indexing
print(x[0,0]) #first row first column
print(x[0,:]) #first row all columns
print(x[:,0])#all rows first column
print(x[:2,:2]) #first 2 rows, first 2 coumns
print(x[:2]) #first 2 rows, all columns

2
[2 3 4]
[2 5]
[[2 3]
 [5 6]]
[[2 3 4]
 [5 6 7]]
